// -------------------------------------------> Headers <-------------------------------------------
    #include "Header/Choices.h"
    #include "Header/ConversionFunction.h"
    #include "Header/ConversionChecks.h"
    #include "Header/Bitwise.h"
    #include "Header/Euclidean.h"
    #include "Header/SieveOfEratosthenes.h"
    #include "Header/PrimeFactorization.h"
    #include "Header/LCDandGCD.h"
    #include "Header/Fibonacci.h"
    #include "Header/EgyptianFraction.h"
    #include "Header/CalculatorandConvertionFunction.h"
    #include "Header/Modular.h"
    #include "Header/CeasarScifer.h"
    #include "Header/DiffieHellman.h"
    #include "Header/RSA.h"
    #include "Header/AES.h"
    #include "Header/DES.h"
    #include "Header/ActivitySelection.h"
    #include "Header/jobsequence.h"
    #include "Header/knapsack.h"
    #include "Header/miceandholes.h"
    #include "Header/huffman.h"

// -------------------------------------------> Headers <-------------------------------------------
