// -------------------------------------------> Headers <-------------------------------------------
    #include "NormalHeaderAlgorithms/Choices.h"
    #include "NormalHeaderAlgorithms/ConversionFunction.h"
    #include "NormalHeaderAlgorithms/ConversionChecks.h"
    #include "NormalHeaderAlgorithms/Bitwise.h"
    #include "NormalHeaderAlgorithms/Euclidean.h"
    #include "NormalHeaderAlgorithms/SieveOfEratosthenes.h"
    #include "NormalHeaderAlgorithms/PrimeFactorization.h"
    #include "NormalHeaderAlgorithms/LCDandGCD.h"
    #include "NormalHeaderAlgorithms/Fibonacci.h"
    #include "NormalHeaderAlgorithms/EgyptianFraction.h"
    #include "NormalHeaderAlgorithms/CalculatorandConvertionFunction.h"
    #include "NormalHeaderAlgorithms/Modular.h"
    #include "Cryptography/CeasarScifer.h"
    #include "Cryptography/DiffieHellman.h"
    #include "Cryptography/RSA.h"
    #include "Cryptography/AES.h"
    #include "Cryptography/DES.h"
    #include "GreedyAlgorithm/ActivitySelection.h"
    #include "GreedyAlgorithm/jobsequence.h"
    #include "GreedyAlgorithm/knapsack.h"
    #include "GreedyAlgorithm/coinchange.h"
    #include "GreedyAlgorithm/miceandholes.h"
    #include "GreedyAlgorithm/huffman.h"
    #include "GreedyAlgorithm/Kruvskal MST.h"
    #include "GreedyAlgorithm/Prim MST.h"
    #include "GreedyAlgorithm/Boruvka MST.h"
    #include "GreedyAlgorithm/Dijikstra MST.h"
    #include "GreedyAlgorithm/Dial.h"

// -------------------------------------------> Headers <-------------------------------------------
